#!/usr/bin/env bash
# AV-STE demo — token comparison tables + Moshi streaming generation.
#
# AV-STE predicted tokens are loaded from examples/predictions_speech.json and
# examples/predictions_nonspeech.json, generated by infer_lrs3_dialog_test.sh
# (av_4lookahead_crossattn_soft_gate checkpoint).
#
# Speech noise sample:    rP7nmdDA1Fg_00006 (snr_neg10)
#   "I THINK WHAT THAT MEANS IS THAT PEOPLE JUST COULDN'T SEE WHAT WAS IN FRONT OF THEM"
# Nonspeech noise sample: MvXZzKZ3JYQ_00001 (snr_neg10)
#   "MY MOTHER WAS ON THE LINE TO TELL ME THAT DOCTORS HAD FOUND A LUMP IN HIS STOMACH TERMINAL CANCER"
#
# Outputs two tables per clip:
#   Table A — token accuracy + WER of Mimi-decoded audio
#   Table B — Moshi streaming generation coherence (transcript of Moshi's response)
#
# Usage:
#   bash examples/run_demo.sh
#
# Environment variables:
#   COMPARE_PYTHON  python with moshi+whisper  (default: python)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

COMPARE_PY="${COMPARE_PYTHON:-python}"

mkdir -p "$ROOT/outputs"

echo "════════════════════════════════════════"
echo " AV-STE Demo — Token comparison & Moshi"
echo "════════════════════════════════════════"
echo ""

# Run comparison and save audio to outputs/compare_audio/
"$COMPARE_PY" "$ROOT/scripts/compare_demo.py" --save_audio

echo ""
echo "────────────────────────────────────────"
echo " To populate the web demo (docs/):"
echo "   cp outputs/compare_audio/*.wav docs/audio/"
echo " Then open docs/index.html in a browser,"
echo " or enable GitHub Pages on the docs/ folder."
echo "────────────────────────────────────────"
