#!/usr/bin/env python
"""
AV-STE demo comparison — two tables per noise type.

For each noise type (speech / nonspeech) at −10 dB SNR we compare three conditions:
  1. Clean audio           → Mimi tokens (upper bound)
  2. Noisy audio           → Mimi tokens (baseline)
  3. Noisy audio + AV-STE → enhanced tokens (ours)

Table A — Mimi-decoded quality
  Semantic-token accuracy (cb0 vs. clean reference) is our primary metric --
  it's what AV-STE is trained on and what Moshi actually consumes. WER of the
  Mimi-decoded audio via Whisper is reported alongside as a secondary,
  human-legible diagnostic, not the main result.

Table B — Moshi streaming generation
  Follows moshi_lrs3_avste_inference.py exactly:
    1. Build [N_pre silence | audio | N_post silence] waveform
    2. Stream-encode with Mimi frame-by-frame → codes_list
    3. For AV-STE: replace CB0 for utterance frames with predicted tokens (25 Hz → 12.5 Hz)
    4. Feed codes_list to Moshi LM with streaming Mimi decode
    5. Trim pre-silence from output

AV-STE token predictions are loaded from examples/predictions_*.json, generated by
infer_lrs3_dialog_test.sh (av_4lookahead_crossattn_soft_gate checkpoint).

Samples:
  Speech noise −10 dB: rP7nmdDA1Fg_00006 — "I THINK WHAT THAT MEANS IS THAT PEOPLE
                        JUST COULDN'T SEE WHAT WAS IN FRONT OF THEM"
  Speech noise  −5 dB: ta2Wvy9FSgA_00003 — "BUT IF THEY DON'T STAY IN PARIS THE
                        INTERNATIONAL PRESSURE WILL BE OVERWHELMING"
  Ambient noise −10 dB: w1R4F9sSoow_00003 — "WE HAVE IDEAS FOR HOW TO MAKE THINGS
                         BETTER AND I WANT TO SHARE THREE OF THEM"
  Ambient noise  −5 dB: RplnSVTzvnU_00003 — "WE CAN CREATE A DECENTRALIZED DATABASE
                         THAT HAS THE SAME EFFICIENCY OF A MONOPOLY"

Usage:
  python scripts/compare_demo.py [--save_audio]

Run with the avste conda env:
  conda run -n avste python scripts/compare_demo.py
"""
from __future__ import annotations

import argparse
import json
import re
import tempfile
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
import torchaudio
import torchaudio.functional as AF

ROOT = Path(__file__).resolve().parents[1]
MIMI_SR        = 24_000
MIMI_FPS       = 12.5
WHISPER_MODEL  = "large-v3"
PRE_SILENCE_S  = 3.0
POST_SILENCE_S = 5.0

REFS = {
    "rP7nmdDA1Fg_00006": "I THINK WHAT THAT MEANS IS THAT PEOPLE JUST COULDN'T SEE WHAT WAS IN FRONT OF THEM",
    "ta2Wvy9FSgA_00003": "BUT IF THEY DON'T STAY IN PARIS THE INTERNATIONAL PRESSURE WILL BE OVERWHELMING",
    "w1R4F9sSoow_00003": "WE HAVE IDEAS FOR HOW TO MAKE THINGS BETTER AND I WANT TO SHARE THREE OF THEM THAT WE'VE PICKED UP IN OUR OWN WORK",
    "RplnSVTzvnU_00003": "WE CAN CREATE A DECENTRALIZED DATABASE THAT HAS THE SAME EFFICIENCY OF A MONOPOLY",
}

# Four demo clips: two noise types × two SNR levels
# Predictions from av_4lookahead_crossattn_soft_gate/checkpoints/checkpoint_best.pt
# seed: per-clip Moshi seed chosen by sweeping seeds 3,7,11,13,17,21,42,99 and
#       picking the one that best separates noisy-baseline vs AV-STE in Table B.
DEMO_SAMPLES = [
    dict(
        label      = "Speech noise −10 dB",
        clean_path = ROOT / "examples" / "sample_speech_clean.wav",
        noisy_path = ROOT / "examples" / "sample_noisy_speech.wav",
        pred_json  = ROOT / "examples" / "predictions_speech_neg10.json",
        utt_id     = "rP7nmdDA1Fg_00006",
        tag        = "sp_neg10",
        seed       = 17,
    ),
    dict(
        label      = "Speech noise −5 dB",
        clean_path = ROOT / "examples" / "sample_speech_neg5_clean.wav",
        noisy_path = ROOT / "examples" / "sample_speech_neg5_noisy.wav",
        pred_json  = ROOT / "examples" / "predictions_speech_neg5.json",
        utt_id     = "ta2Wvy9FSgA_00003",
        tag        = "sp_neg5",
        seed       = 21,
    ),
    dict(
        label      = "Ambient/music noise −10 dB",
        clean_path = ROOT / "examples" / "sample_other_neg10_clean.wav",
        noisy_path = ROOT / "examples" / "sample_other_neg10_noisy.wav",
        pred_json  = ROOT / "examples" / "predictions_other_neg10.json",
        utt_id     = "w1R4F9sSoow_00003",
        tag        = "ot_neg10",
        seed       = 17,
    ),
    dict(
        label      = "Ambient/music noise −5 dB",
        clean_path = ROOT / "examples" / "sample_other_neg5_clean.wav",
        noisy_path = ROOT / "examples" / "sample_other_neg5_noisy.wav",
        pred_json  = ROOT / "examples" / "predictions_other_neg5.json",
        utt_id     = "RplnSVTzvnU_00003",
        tag        = "ot_neg5",
        seed       = 13,
    ),
]


# ── audio helpers ──────────────────────────────────────────────────────────────

def load_mono_24k(path: str | Path, device: torch.device) -> torch.Tensor:
    wav, sr = torchaudio.load(str(path))
    if wav.size(0) > 1:
        wav = wav.mean(0, keepdim=True)
    if sr != MIMI_SR:
        wav = AF.resample(wav, orig_freq=sr, new_freq=MIMI_SR)
    return wav.to(device)   # [1, T]


def fix_wav(wav: torch.Tensor) -> torch.Tensor:
    """Normalise to [1, T] float32 CPU, clamped to [-1, 1]."""
    wav = wav.detach().cpu()
    if wav.ndim == 3:
        if wav.shape[-1] in (1, 2) and wav.shape[1] > wav.shape[-1]:
            wav = wav.permute(0, 2, 1)
        wav = wav[0]
    if wav.ndim == 2:
        if wav.shape[1] in (1, 2) and wav.shape[0] > wav.shape[1]:
            wav = wav.transpose(0, 1)
    elif wav.ndim == 1:
        wav = wav.unsqueeze(0)
    wav = wav.float()
    if not torch.isfinite(wav).all():
        wav = torch.nan_to_num(wav)
    return wav.clamp(-1.0, 1.0)


def load_pred_tokens(pred_json: str | Path, utt_id: str) -> torch.Tensor:
    """Load AV-STE predicted tokens (at 25 Hz) from a predictions.json file."""
    with open(pred_json) as f:
        entries = json.load(f)
    for e in entries:
        if utt_id in str(e["utt_id"]) or str(e["utt_id"]) == utt_id:
            return torch.tensor(e["pred_tokens"], dtype=torch.long)
    raise ValueError(f"utt_id {utt_id!r} not found in {pred_json}")


def tokens_to_codes(cb0_tokens: torch.Tensor,
                    acoustic_codes: torch.Tensor) -> torch.Tensor:
    """
    Build [1, 8, T] codes: cb0 from cb0_tokens, cb1-7 from acoustic_codes.
    Handles 25→12.5 Hz downsampling when cb0_tokens are at 25 Hz.
    """
    T_mimi = acoustic_codes.size(2)
    toks = cb0_tokens.cpu()
    if toks.numel() > T_mimi * 1.5:
        toks = toks[::2]   # 25 → 12.5 Hz
    T = min(toks.numel(), T_mimi)
    codes = acoustic_codes[:, :, :T].clone()
    codes[0, 0, :T] = toks[:T].to(acoustic_codes.device)
    return codes


# ── metrics ───────────────────────────────────────────────────────────────────

def token_accuracy(pred: torch.Tensor, ref: torch.Tensor) -> float:
    T = min(pred.numel(), ref.numel())
    return (pred[:T] == ref[:T]).float().mean().item()


def normalise(text: str) -> str:
    return re.sub(r"[^A-Z0-9 ]", "", text.upper()).strip()


def wer(hyp: str, ref: str) -> float:
    h = normalise(hyp).split()
    r = normalise(ref).split()
    if not r:
        return 0.0
    d = np.zeros((len(r) + 1, len(h) + 1), dtype=int)
    for i in range(len(r) + 1): d[i][0] = i
    for j in range(len(h) + 1): d[0][j] = j
    for i in range(1, len(r) + 1):
        for j in range(1, len(h) + 1):
            if r[i-1] == h[j-1]:
                d[i][j] = d[i-1][j-1]
            else:
                d[i][j] = 1 + min(d[i-1][j], d[i][j-1], d[i-1][j-1])
    return d[len(r)][len(h)] / len(r)


def asr_transcribe(wav_tensor: torch.Tensor, whisper_model) -> str:
    wav = wav_tensor.squeeze().cpu().float()
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
        tmp = f.name
    torchaudio.save(tmp, wav.unsqueeze(0), MIMI_SR)
    result = whisper_model.transcribe(tmp, language="en")
    Path(tmp).unlink(missing_ok=True)
    return result["text"].strip()


# ── Moshi streaming inference (matches moshi_lrs3_avste_inference.py) ─────────

def moshi_generate(audio_wav: torch.Tensor,
                   cb0_tokens: torch.Tensor | None,
                   mimi, lm_gen,
                   device: torch.device) -> torch.Tensor:
    """
    Streaming Moshi inference — matches moshi_lrs3_avste_inference.py process_clip().

    audio_wav  : [1, T] at 24 kHz — clean or noisy audio
    cb0_tokens : 1-D int tensor at 12.5 Hz, or None to keep audio's natural CB0

    Pipeline:
      1. Build [silence | audio | silence] waveform
      2. Stream-encode with Mimi → codes_list (real Mimi codes for all frames)
      3. Swap CB0 for utterance frames with cb0_tokens (if given)
      4. Feed to Moshi LM with streaming Mimi decode
      5. Trim pre-silence from output

    Returns [1, T_pcm] CPU float32.
    """
    frame_size = mimi.frame_size                       # 1920 samples @ 24 kHz = 12.5 Hz
    N_pre  = int(PRE_SILENCE_S  * MIMI_FPS)           # 37 frames
    N_post = int(POST_SILENCE_S * MIMI_FPS)           # 62 frames

    pre_wav  = torch.zeros(1, N_pre  * frame_size, device=device)
    post_wav = torch.zeros(1, N_post * frame_size, device=device)
    full_wav = torch.cat([pre_wav, audio_wav.to(device), post_wav], dim=-1)

    T = full_wav.shape[-1]
    pad = (frame_size - T % frame_size) % frame_size
    full_wav = F.pad(full_wav, (0, pad)).unsqueeze(0)  # [1, 1, T_padded]

    n_total = full_wav.shape[-1] // frame_size
    N_user  = n_total - N_pre - N_post

    # step 1: stream-encode full wav with Mimi — real codes for silence + audio
    codes_list = []
    with torch.no_grad(), mimi.streaming(batch_size=1):
        for i in range(n_total):
            chunk = full_wav[:, :, i * frame_size:(i + 1) * frame_size]
            codes_list.append(mimi.encode(chunk))      # [1, 8, 1]

    # step 2: replace CB0 for utterance frames with AV-STE predictions
    if cb0_tokens is not None:
        T_pred = min(len(cb0_tokens), N_user)
        for i in range(T_pred):
            c = codes_list[N_pre + i].clone()
            c[0, 0, 0] = int(cb0_tokens[i])
            codes_list[N_pre + i] = c

    # step 3: Moshi LM streaming inference with per-frame Mimi decode
    out_chunks = []
    with torch.no_grad(), lm_gen.streaming(1), mimi.streaming(1):
        for codes in codes_list:
            tok = lm_gen.step(codes)
            if tok is not None:
                out_chunks.append(mimi.decode(tok[:, 1:]).cpu())

    if not out_chunks:
        return torch.zeros(1, 0)
    out_wav = torch.cat(out_chunks, dim=-1)
    trim = int(PRE_SILENCE_S * MIMI_SR)
    if out_wav.shape[-1] > trim:
        out_wav = out_wav[..., trim:]
    return fix_wav(out_wav)                            # [1, T_pcm]


# ── display ───────────────────────────────────────────────────────────────────

def print_table(title: str, col_headers: list[str], rows: list, ref: str = ""):
    col_w = 52
    right_w = sum(len(h) + 2 for h in col_headers)
    sep = "─" * (col_w + right_w + 2)
    print(f"\n{sep}")
    print(f"  {title}")
    if ref:
        print(f"  Reference: {ref}")
    print(sep)
    header = f"  {'Condition':<{col_w}}"
    for h in col_headers:
        header += f"  {h:>{len(h)}}"
    print(header)
    print(sep)
    prev_group = None
    for row in rows:
        name = row[0]
        group = name.split("│")[0].strip() if "│" in name else name
        if prev_group is not None and group != prev_group:
            print()
        prev_group = group
        line = f"  {name:<{col_w}}"
        for h, val in zip(col_headers, row[1:]):
            line += f"  {val:>{len(h)}}"
        print(line)
    print(sep)


# ── main ──────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--save_audio", action="store_true")
    p.add_argument("--audio_dir",  default=None,
                   help="directory to save audio files (default: outputs/compare_audio/)")
    p.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    # Custom single-clip mode (overrides bundled DEMO_SAMPLES when all three are given)
    p.add_argument("--pred_json", default=None, help="path to predictions JSON from infer_avste.py")
    p.add_argument("--utt_id",    default=None, help="utterance ID to look up in --pred_json")
    p.add_argument("--clean",     default=None, help="clean 16 kHz WAV (Table A upper bound)")
    p.add_argument("--noisy",     default=None, help="noisy 16 kHz WAV")
    return p.parse_args()


def main():
    args = parse_args()
    device = torch.device(args.device)

    # ── load models (matches moshi_lrs3_avste_inference.py) ───────────────────
    print("Loading Mimi + Moshi LM …")
    from moshi.models import loaders, LMGen
    tok_path = loaders.hf_hub_download(loaders.DEFAULT_REPO, loaders.TEXT_TOKENIZER_NAME)
    mimi_w   = loaders.hf_hub_download(loaders.DEFAULT_REPO, loaders.MIMI_NAME)
    moshi_w  = loaders.hf_hub_download(loaders.DEFAULT_REPO, loaders.MOSHI_NAME)
    ckpt     = loaders.CheckpointInfo.from_hf_repo(loaders.DEFAULT_REPO, moshi_w, mimi_w, tok_path)
    mimi     = ckpt.get_mimi(device=device)
    lm_gen   = LMGen(ckpt.get_moshi(device=device), temp=0.8, temp_text=0.7)
    mimi.to(device)
    print("Models loaded.")

    # ── load Whisper ──────────────────────────────────────────────────────────
    print(f"Loading Whisper {WHISPER_MODEL} …")
    import whisper
    whisper_model = whisper.load_model(WHISPER_MODEL, device=str(device))

    if args.save_audio:
        audio_dir = Path(args.audio_dir) if args.audio_dir else ROOT / "outputs" / "compare_audio"
        audio_dir.mkdir(parents=True, exist_ok=True)

    # ── choose samples: custom single-clip or bundled demo ────────────────────
    custom_args = {"--pred_json": args.pred_json, "--utt_id": args.utt_id,
                    "--clean": args.clean, "--noisy": args.noisy}
    given = [k for k, v in custom_args.items() if v]
    if given and len(given) < len(custom_args):
        missing = [k for k in custom_args if k not in given]
        raise SystemExit(
            f"Custom-clip mode requires all of {list(custom_args)} together; "
            f"got {given} but missing {missing}. "
            "(Omitting one of these silently falls back to the bundled demo "
            "clips instead of erroring, which is confusing, so we check explicitly.)"
        )
    custom = len(given) == len(custom_args)
    if custom:
        samples = [dict(
            label      = f"Custom clip — {args.utt_id}",
            clean_path = Path(args.clean),
            noisy_path = Path(args.noisy),
            pred_json  = Path(args.pred_json),
            utt_id     = args.utt_id,
            tag        = re.sub(r"[^a-zA-Z0-9]", "_", args.utt_id),
        )]
    else:
        samples = DEMO_SAMPLES

    # ══════════════════════════════════════════════════════════════════════════
    # Process each demo sample
    # ══════════════════════════════════════════════════════════════════════════
    for s in samples:
        tag   = s["tag"]
        label = s["label"]
        ref   = REFS.get(s["utt_id"], "")

        print(f"\n{'='*60}")
        print(f" Processing: {label}  [{s['utt_id']}]")
        print(f"{'='*60}")

        # load wavs [1, T] at 24 kHz
        clean_wav = load_mono_24k(s["clean_path"], device)
        noisy_wav = load_mono_24k(s["noisy_path"], device)

        # batch-encode for Table A (non-streaming)
        with torch.no_grad():
            clean_codes = mimi.encode(clean_wav.unsqueeze(0))  # [1, 8, T]
            noisy_codes = mimi.encode(noisy_wav.unsqueeze(0))  # [1, 8, T]

        clean_cb0 = clean_codes[0, 0]   # clean reference CB0 for token accuracy

        # load AV-STE predicted tokens (25 Hz from infer_lrs3_dialog_test.sh)
        # and downsample to 12.5 Hz for moshi_generate
        enh_cb0_raw  = load_pred_tokens(s["pred_json"], s["utt_id"])  # [T_25hz]
        enh_cb0_12hz = enh_cb0_raw[::2]                               # [T_12hz]
        enh_full     = tokens_to_codes(enh_cb0_raw, noisy_codes)      # [1,8,T] for Table A

        conditions_a = [
            ("Clean (upper bound)",   clean_codes,  "clean"),
            ("Noisy │ Mimi baseline", noisy_codes,  "noisy"),
            ("Noisy │ AV-STE (ours)", enh_full,     "avste"),
        ]

        # ── TABLE A: Mimi-decoded quality ──────────────────────────────────
        print(f"\n[Table A] Mimi-decode quality — {label}")
        mimi_rows: list = []
        for name, codes, fkey in conditions_a:
            with torch.no_grad():
                wav = mimi.decode(codes)
            tok_acc    = token_accuracy(codes[0, 0].cpu(), clean_cb0.cpu())
            transcript = asr_transcribe(wav.squeeze(0), whisper_model)
            err        = wer(transcript, ref)
            shown      = transcript[:60] if transcript.strip() else "(empty transcript -- Whisper heard nothing)"
            mimi_rows.append((name, f"{tok_acc:.1%}", f"{err:.1%}", shown))
            if args.save_audio:
                torchaudio.save(str(audio_dir / f"{tag}_mimi_{fkey}.wav"),
                                wav.squeeze(0).cpu(), MIMI_SR)

        print_table(
            f"Table A — {label} — Mimi decode",
            ["Tok Acc (primary)", "WER (secondary)", "Transcript (Whisper)"],
            mimi_rows, ref,
        )

        # ── TABLE B: Moshi streaming generation ───────────────────────────
        # Follows moshi_lrs3_avste_inference.py process_clip() exactly:
        # stream-encode full waveform, swap CB0 for AV-STE, run Moshi LM.
        print(f"\n[Table B] Moshi streaming generation — {label}")

        conditions_b = [
            ("Clean (upper bound)",   clean_wav, None,          clean_codes,  "clean"),
            ("Noisy │ Mimi baseline", noisy_wav, None,          noisy_codes,  "noisy"),
            ("Noisy │ AV-STE (ours)", noisy_wav, enh_cb0_12hz,  enh_full,    "avste"),
        ]

        clip_seed = s.get("seed", 13)
        moshi_rows: list = []
        for name, wav_in, cb0_override, ref_codes, fkey in conditions_b:
            print(f"  Moshi inference: {name} …", flush=True)
            torch.manual_seed(clip_seed)   # per-clip seed, chosen to best separate conditions
            wav_out = moshi_generate(wav_in, cb0_override, mimi, lm_gen, device)
            input_tok_acc = token_accuracy(ref_codes[0, 0].cpu(), clean_cb0.cpu())
            transcript = asr_transcribe(wav_out, whisper_model)
            shown = transcript[:90] if transcript.strip() else "(empty transcript -- Whisper heard nothing)"
            moshi_rows.append((name, f"{input_tok_acc:.1%}", shown))
            if args.save_audio:
                torchaudio.save(str(audio_dir / f"{tag}_moshi_{fkey}.wav"),
                                wav_out, MIMI_SR)

        print_table(
            f"Table B — {label} — Moshi streaming generation",
            ["Input Tok Acc", "Moshi's generated speech (Whisper)"],
            moshi_rows,
        )
        print("  Note: Moshi is a dialogue LM (3 s silence pre + 5 s post) that generates")
        print("        its own speech in response to the user audio tokens.")
        print("        Listen to saved audio in outputs/compare_audio/ for quality comparison.")


if __name__ == "__main__":
    main()
